### ISSUE TITLE
Update example project?

### ISSUE THREAD

**Issue by philippeowagner** [collinmutembei/django-background-tasks-example#3]
We pushed a more stable and robust version of django-background-tasks to the Python Package Index today.

What about updating the example project and it's requirements to https://github.com/arteria/django-background-tasks/releases/tag/v1.1.6 ?

**Comment by hnakamur** [comment]
Congratulations for the new release and thanks for letting me know.
I'm afraid I have not used django-background-tasks or django these days.
It would be great if you take over the ownership of this example repository.

**Comment by collinmutembei** [comment]
Hi @hnakamur, I am interested in maintaining the example project.

I have taken the initiative to update the requirements and submit #4. Let me know what you think.

**Comment by hnakamur** [comment]
Hi @collinmutembei, thank you for your kind offer!
I'm happy to transfer the ownership of this project.
Do you want this project to be transfered to your github account or
do you create a github organization for this project?

Also thank your for your pull request #4! I've just merged it.

**Comment by collinmutembei** [comment]
Transfer it to my account. Thank you.

**Comment by hnakamur** [comment]
I failed to transfer this project to your account with the following error message:
collinmutembei/django-background-tasks-example already exists

Could you remove your project?
Thanks!

**Comment by collinmutembei** [comment]
Oh! that's because of the fork I made. Renamed it, try again.

**Comment by hnakamur** [comment]
Failed again with the following error message this time:
collinmutembei already has a repository in the hnakamur/django-background-tasks-example network

Maybe you need to remove it instead of renaming it.

**Comment by collinmutembei** [comment]
On it, removed it.

**Comment by hnakamur** [comment]
Thank you!
This time I succeeded to transfer the repository with the following message:
Repository transfer to collinmutembei requested

I suppose you will receive a request to take ownership of this project.

* [About repository transfers - User Documentation](https://help.github.com/articles/about-repository-transfers/)
* [Transferring a repository owned by your personal account - User Documentation](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

**Comment by collinmutembei** [comment]
Accepted. Thank you @hnakamur, keep in touch.

**Comment by hnakamur** [comment]
Thank you again for maintaining this example project!
I'm closing this issue now.

**Comment by philippeowagner** [comment]
Thanks @hnakamur for creating this example project and thanks @collinmutembei to keep it going on... 

We do continuously investing into [django-background-tasks](https://github.com/arteria/django-background-tasks) to make it better and more robust. An update for Django 1.11 will be available within days.

This example really helps to get an own project up and running or just try django-background-tasks quickly. It's great to see, that this example project is important for others as well! Thanks again. 😄
