### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kayhayen** [collinmutembei/django-background-tasks-example#7]
First an observation. Due to using 2 processes, I think this excludes using sqlite databases, as they have exclusive locks. Is that correct?

Second, I was looking at models.py and didn't see any tables described. I was surprised. This means that when restarted, there is no state for tasks, they will need to be newly scheduled.

My intended use case is to allow the user to add tasks to import information, which will be very long running and good as a separate, non-blocking process, much like run-tasks is. I really would want that information to be persistent, as some of these tasks are more like continuous observations.

Now I wonder (also since the example doesn't run for me, see other issue) if there is any value at all in background tasks, maybe because I lack Django knowledge. Will I not be able to import models from the second app in another project, even multiple processes, and insert data and execute tasks with say cron/at or systemd timers instead.

I didn't go deep enough to see it in the code, but what method of IPC, if not the database, is runtasks using to talk to runserver, and how does it interact with wsgi. I am kind of thinking I just missed out on the model.

**Comment by collinmutembei** [comment]
@kayhayen 
> First an observation. Due to using 2 processes, I think this excludes using sqlite databases, as they have exclusive locks. Is that correct?

The test project actually uses an sqlite database. 
https://github.com/collinmutembei/django-background-tasks-example/blob/543f6c753ba7f4d8b5d2fdc3148ef8bb4d4a0ac0/project/project/settings.py#L79-L84
> Second, I was looking at models.py and didn't see any tables described. I was surprised. This means that when restarted, there is no state for tasks, they will need to be newly scheduled.

Tasks created are persisted in the database under a table named `background_task` while completed tasks can be found in `background_task_completedtask`. These tables are created by the [`django-background-tasks`](https://github.com/arteria/django-background-tasks/) package, not under *Models.py* for this project.

I am confident that `django-background-tasks` will satisfy requirements for your use case. I recommend that you have a look through the code for this test project to get an overview of how everything plugs together. Further information can be found on django-background-tasks [documentation](http://django-background-tasks.readthedocs.io/en/latest/) pages.
